CREATE TABLE CUSTOMER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NULL,
    PHONE_NUMBER VARCHAR(255) NULL,
    PRIMARY KEY (ID)
);
